tradFlower = {
    "anthurium": ("anthurium", "https://fr.wikipedia.org/wiki/Anthurium"),
    "artichoke": ("artichaut", "https://fr.wikipedia.org/wiki/Artichaut"),
    "azalea": ("rhododendron", "https://fr.wikipedia.org/wiki/Rhododendron"),
    "balloon flower": ("platycodon grandiflorus", "https://fr.wikipedia.org/wiki/Platycodon_grandiflorus"),
    "barberton daisy": ("margueritte de Barberton", "https://en.wikipedia.org/wiki/Gerbera_jamesonii"),
    "bee balm": ("monarda", "https://fr.wikipedia.org/wiki/Monarda"),
    "bird of paradise": ("oiseau de paradis", "https://fr.wikipedia.org/wiki/Strelitzia_reginae"),
    "bishop of llandaff": ("dahlia 'Bishop of Llandaff'", "https://en.wikipedia.org/wiki/Dahlia_'Bishop_of_Llandaff'"),
    "black-eyed susan": ("Suzanne aux yeux noirs", "https://fr.wikipedia.org/wiki/Rudbeckia_hirta"),
    "bougainvillea": ("bougainvillea", "https://fr.wikipedia.org/wiki/Bougainvillea"),
    "buttercup": ("bouton d'or", "https://fr.wikipedia.org/wiki/Renoncule"),
    "californian poppy": ("pavot de Californie", "https://fr.wikipedia.org/wiki/Pavot_de_Californie"),
    "camellia": ("camélia", "https://fr.wikipedia.org/wiki/Camellia"),
    "cape flower": ("amaryllis", "https://fr.wikipedia.org/wiki/Amaryllis"),
    "carnation": ("oeillet commun", "https://fr.wikipedia.org/wiki/%C5%92illet_commun"),
    "clematis": ("clématite", "https://fr.wikipedia.org/wiki/Cl%C3%A9matite"),
    "columbine": ("ancolies", "https://fr.wikipedia.org/wiki/Ancolie"),
    "common dandelion": ("pissenlit", "https://fr.wikipedia.org/wiki/Taraxacum"),
    "common tulip": ("tulipe", "https://fr.wikipedia.org/wiki/Tulipe"),
    "corn poppy": ("coquelicot", "https://fr.wikipedia.org/wiki/Coquelicot"),
    "cylamen": ("cylamen", "https://fr.wikipedia.org/wiki/Cyclamen"),
    "daffodil": ("jonquilles", "https://fr.wikipedia.org/wiki/Narcissus"),
    "daisy": ("pâquerette", "https://fr.wikipedia.org/wiki/P%C3%A2querette"),
    "foxglove": ("digitale", "https://fr.wikipedia.org/wiki/Digitale"),
    "frangipani": ("frangipanier", "https://fr.wikipedia.org/wiki/Plumeria"),
    "gaura": ("gaura", "https://fr.wikipedia.org/wiki/Gaura"),
    "gazania": ("gazanie", "https://fr.wikipedia.org/wiki/Gazania"),
    "geranium": ("geranium", "https://fr.wikipedia.org/wiki/Geranium"),
    "globe thistle": ("echinops", "https://fr.wikipedia.org/wiki/Echinops"),
    "grape hyacinth": ("jacinthes à grappes", "https://fr.wikipedia.org/wiki/Muscari"),
    "hibiscus": ("hibiscus", "https://fr.wikipedia.org/wiki/Hibiscus"),
    "hippeastrum": ("hippéastre", "https://fr.wikipedia.org/wiki/Hippeastrum"),
    "iris": ("iris", "https://fr.wikipedia.org/wiki/Iris_(genre_v%C3%A9g%C3%A9tal)"),
    "king protea": ("protea cynaroides", "https://fr.wikipedia.org/wiki/Protea_cynaroides"),
    "lenten rose": ("hellébore", "https://fr.wikipedia.org/wiki/Helleborus"),
    "lotus": ("lotus", "https://fr.wikipedia.org/wiki/Nelumbo_nucifera"),
    "magnolia": ("magnolia", "https://fr.wikipedia.org/wiki/Magnolia"),
    "mallow": ("malvacé", "https://fr.wikipedia.org/wiki/Malvaceae"),
    "marigold": ("candendula", "https://fr.wikipedia.org/wiki/Calendula"),
    "monkshood": ("aconit", "https://fr.wikipedia.org/wiki/Aconitum"),
    "morning glory": ("belle de jour", "https://fr.wikipedia.org/wiki/Belle-de-jour_(plante)"),
    "passion flower": ("passiflore", "https://fr.wikipedia.org/wiki/Passiflore"),
    "peruvian lily": ("alstroemère", "https://fr.wikipedia.org/wiki/Alstroemeria"),
    "petunia": ("petunia", "https://fr.wikipedia.org/wiki/Petunia"),
    "pincushion flower": ("chaenactis", "https://fr.wikipedia.org/wiki/Chaenactis"),
    "pink primrose": ("oenothera speciosa", "https://fr.wikipedia.org/wiki/Oenothera_speciosa"),
    "pink-yellow dahlia": ("dahlia rose-jaune", "https://fr.wikipedia.org/wiki/Dahlia"),
    "poinsettia": ("étoile de noël", "https://fr.wikipedia.org/wiki/Euphorbia_pulcherrima"),
    "primula": ("primevère", "https://fr.wikipedia.org/wiki/Primev%C3%A8re"),
    "purple coneflower": ("échinacée pourpre", "https://fr.wikipedia.org/wiki/Echinacea_purpurea"),
    "rose": ("rose", "https://fr.wikipedia.org/wiki/Rose_(fleur)"),
    "snapdragon": ("gueule de loup", "https://fr.wikipedia.org/wiki/Antirrhinum"),
    "spear thistle": ("cirse", "https://fr.wikipedia.org/wiki/Cirse_commun"),
    "sunflower": ("tournesol", "https://fr.wikipedia.org/wiki/H%C3%A9lianthe"),
    "sweet william": ("oeillet de poète", "https://fr.wikipedia.org/wiki/%C5%92illet_de_po%C3%A8te"),
    "sword lily": ("glaïeul", "https://fr.wikipedia.org/wiki/Gla%C3%AFeul"),
    "thorn apple": ("stramoine", "https://fr.wikipedia.org/wiki/Datura_stramonium"),
    "tiger lily": ("lis tigré", "https://fr.wikipedia.org/wiki/Lilium_lancifolium"),
    "toad lily": ("lis crapaud", "https://fr.wikipedia.org/wiki/Tricyrtis"),
    "tree poppy": ("coquelicot blanc", "https://fr.wikipedia.org/wiki/Coquelicot_blanc"),
    "wallflower": ("vélar", "https://fr.wikipedia.org/wiki/V%C3%A9lar"),
    "watercress": ("cresson", "https://fr.wikipedia.org/wiki/Cresson_(plante)"),
    "water lily": ("lis d'eau", "https://fr.wikipedia.org/wiki/Nymphaeaceae"),
    "wild geranium": ("géranium sauvage", "https://en.wikipedia.org/wiki/Geranium_maculatum"),
    "wild pansy": ("pensée sauvage", "https://fr.wikipedia.org/wiki/Viola_tricolor"),
    "wild rose": ("rosier de l'Arkansas", "https://fr.wikipedia.org/wiki/Rosa_arkansana"),
    "windflower": ("anémone sylvie", "https://fr.wikipedia.org/wiki/An%C3%A9mone_sylvie"),
    "yellow iris": ("iris jaune", "https://fr.wikipedia.org/wiki/Iris_pseudacorus"),
}
